name: linting, testing, building

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pipeline:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install modules with Yarn
              run: yarn install
            - name: Build production project
              run: yarn run build:prod
              if: always()
            - name: Linting TypeScript
              run: yarn run lint:ts
              if: always()
            - name: Linting CSS
              run: yarn run lint:scss
            - name: Unit testing
              if: always()
              run: yarn run test
            - name: Build Storybook
              run: yarn run storybook:build
              if: always()
